name: Auto Generate Lua Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [lua有更新]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 设置写权限，以便推送标签
      packages: write # 如果发布到 GitHub Packages，需要此权限

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run script
      run: python src/main.py


    - name: Create Dynamic Tag
      id: tag_version
      run: |
        VERSION=$(date +'%Y%m%d%H%M%S')  
        echo "VERSION=v$VERSION" >> $GITHUB_ENV
        git tag "v$VERSION"  # 创建标签
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git push origin "v$VERSION"  # 推送标签

    - name: Set Release Title  # title
      id: set_title
      run: |
        echo "RELEASE_TITLE=Release $(TZ='Asia/Shanghai' date +'%Y%m%d %H:%M')" >> $GITHUB_ENV


    - name: Create Release  
      id: create_release  
      uses: marvinpinto/action-automatic-releases@latest  
      with:  
        automatic_release_tag: ${{ env.VERSION }}  # 使用动态版本号
        repo_token: "${{ secrets.GITHUB_TOKEN }}"  
        prerelease: false  
        title: ${{ env.RELEASE_TITLE }}
        files: |  
          luascripts_android
          luascripts_ios
        include_source_code: false  # 不包括源代码